"""Canonical command-family migrations for removed flat CLI commands."""

from __future__ import annotations


COMMAND_ALIAS_PREFIXES: dict[tuple[str, ...], str] = {
    ("mutable", "inspect", "graph"): "inspect-customizable-object-graph",
    ("mutable", "inspect", "parameters"): "inspect-mutable-parameters",
    ("mutable", "inspect", "diagnostics"): "inspect-mutable-diagnostics",
    ("mutable", "graph", "add-node"): "add-co-node",
    ("mutable", "graph", "add-parameter"): "add-co-parameter",
    ("mutable", "graph", "add-mesh-option"): "add-co-mesh-option",
    ("mutable", "graph", "set-base-mesh"): "set-co-base-mesh",
    ("mutable", "graph", "add-group-child"): "add-co-group-child",
    ("mutable", "graph", "set-node-property"): "set-co-node-property",
    ("mutable", "graph", "connect-pins"): "connect-co-pins",
    ("mutable", "graph", "regenerate-node-pins"): "regenerate-co-node-pins",
    ("mutable", "graph", "remove-node"): "remove-co-node",
    ("mutable", "graph", "create-from-spec"): "create-co-from-spec",
    ("mutable", "graph", "wire-slot-from-table"): "wire-customizable-object-slot-from-table",
    ("mutable", "compile"): "compile-co",
    ("statetree", "inspect"): "query-statetree",
    ("statetree", "state", "add"): "add-statetree-state",
    ("statetree", "state", "remove"): "remove-statetree-state",
    ("statetree", "task", "add"): "add-statetree-task",
    ("statetree", "transition", "add"): "add-statetree-transition",
    ("anim", "instance", "inspect"): "inspect-anim-instance",
    ("anim", "sync-marker", "inspect"): "inspect-sync-markers",
    ("anim", "sync-marker", "compare"): "compare-sync-markers",
    ("anim", "sync-marker", "add"): "add-sync-marker",
    ("anim", "sync-marker", "remove"): "remove-sync-marker",
    ("anim", "state-machine", "add"): "add-anim-state-machine",
    ("anim", "state", "add"): "add-anim-state",
    ("anim", "transition", "add"): "add-anim-transition",
    ("anim", "retarget", "repoint-references"): "anim-repoint-references",
    ("anim", "retarget", "blueprint"): "anim-retarget-blueprint",
    ("anim", "pose-search", "inspect"): "pose-search-schema-inspect",
    ("anim", "pose-search", "remap"): "pose-search-schema-remap",
    ("anim", "pose-search", "database-repoint"): "pose-search-database-repoint",
    ("anim", "rewind", "start"): "rewind-start",
    ("anim", "rewind", "stop"): "rewind-stop",
    ("anim", "rewind", "status"): "rewind-status",
    ("anim", "rewind", "list-tracks"): "rewind-list-tracks",
    ("anim", "rewind", "overview"): "rewind-overview",
    ("anim", "rewind", "snapshot"): "rewind-snapshot",
    ("anim", "rewind", "save"): "rewind-save",
    ("asset", "query"): "query-asset",
    ("asset", "delete"): "delete-asset",
    ("asset", "release-lock"): "release-asset-lock",
    ("asset", "diff"): "get-asset-diff",
    ("asset", "preview"): "get-asset-preview",
    ("asset", "open"): "open-asset",
    ("asset", "set-property"): "set-asset-property",
    ("asset", "repoint-references"): "asset-repoint-references",
    ("asset", "inspect-file"): "inspect-uasset",
    ("asset", "diff-file"): "diff-uasset",
    ("asset", "save"): "save-asset",
    ("asset", "create"): "create-asset",
    ("asset", "skeletal-socket", "create"): "skeletal-mesh-socket-create",
    ("asset", "skeletal-socket", "remove"): "skeletal-mesh-socket-remove",
    ("blueprint", "inspect"): "query-blueprint",
    ("blueprint", "graph", "inspect"): "query-blueprint-graph",
    ("blueprint", "compile"): "compile-blueprint",
    ("blueprint", "node", "add"): "add-graph-node",
    ("blueprint", "node", "remove"): "remove-graph-node",
    ("blueprint", "node", "position"): "set-node-position",
    ("blueprint", "node", "property"): "set-node-property",
    ("blueprint", "pin", "connect"): "connect-graph-pins",
    ("blueprint", "pin", "disconnect"): "disconnect-graph-pin",
    ("blueprint", "interface", "modify"): "modify-interface",
    ("automation", "tests", "run"): "run-automation-tests",
    ("umg", "runtime", "inspect"): "inspect-runtime-widgets",
}


CANONICAL_COMMAND_FOR_REMOVED: dict[str, str] = {}
for _prefix, _legacy_command in COMMAND_ALIAS_PREFIXES.items():
    CANONICAL_COMMAND_FOR_REMOVED.setdefault(_legacy_command, " ".join(_prefix))


REMOVED_COMMAND_MIGRATIONS: dict[str, str] = {
    **CANONICAL_COMMAND_FOR_REMOVED,
    "apply-widget-tree": "umg designer apply",
    "inspect-widget-blueprint": "umg designer inspect",
    "wire-widget-navigation": "umg navigation wire",
    "verify-umg-workflow": "umg workflow run",
    "extract-umg-layout": "umg layout extract",
    "compare-umg-layout": "umg layout compare --mode geometry",
    "compare-umg-screenshot": "umg layout compare --mode pixel",
    "umg-layout": "umg layout",
    "capture-viewport": "capture viewport",
    "capture-screenshot": "capture screenshot --source <mode>",
    "capture-pie-screenshot": "capture screenshot --source pie-window",
}
